# -*- coding: utf-8 -*-
"""AI_Guard_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nps_ksAaD_NhwOkcBzXmbHS5HeoPbWyi

# Imports
"""

!apt-get -qq install graphviz

pip install -q deepface google-generativeai graphviz langgraph kokoro

pip install -q --upgrade transformers

import torch
from deepface import DeepFace
import torchaudio
import cv2
import matplotlib.pyplot as plt
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq , AutoModelForSeq2SeqLM, pipeline
import google.generativeai as genai
from google.colab import userdata
import soundfile as sf
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage, AIMessage
from langchain.memory import ConversationBufferMemory
from IPython.display import Javascript, display, Audio
from google.colab.output import eval_js
from base64 import b64decode
from kokoro import KPipeline
import tempfile
from PIL import Image
from graphviz import Digraph
import io, base64, time, numpy as np
import os
from pathlib import Path
from google.colab import drive
drive.mount('/content/drive')

"""# Media Data"""

class ColabMedia:
    """
    A utility class for handling multimedia I/O directly in Google Colab notebooks.
    It supports microphone recording, webcam frame capture, image saving,
    and audio playback — enabling quick experiments with multimodal inputs.
    """

    def __init__(self, webcam_rate=1.0):
        self.webcam_rate = webcam_rate
        self.last_audio = None
        self.last_frame = None

    def get_audio_input(self, duration=4, filename="audio_input.wav"):
        js = Javascript(f'''
        async function recordAudio() {{
          const stream = await navigator.mediaDevices.getUserMedia({{audio: true}});
          const recorder = new MediaRecorder(stream);
          const chunks = [];
          recorder.ondataavailable = e => chunks.push(e.data);
          recorder.start();
          await new Promise(r => setTimeout(r, {duration*1000}));
          recorder.stop();
          await new Promise(r => recorder.onstop = r);
          const blob = new Blob(chunks);
          const arrayBuffer = await blob.arrayBuffer();
          const base64Audio = btoa(String.fromCharCode(...new Uint8Array(arrayBuffer)));
          return base64Audio;
        }}
        recordAudio();
        ''')
        display(js)
        audio_b64 = eval_js('recordAudio()')
        audio_bytes = base64.b64decode(audio_b64)
        with open(filename, "wb") as f:
            f.write(audio_bytes)
        self.last_audio = filename
        return filename

    def capture_webcam_frame(self):
        js = Javascript('''
        async function captureFrame() {
          const video = document.createElement('video');
          const stream = await navigator.mediaDevices.getUserMedia({video: true});
          video.srcObject = stream;
          await video.play();
          await new Promise(r => setTimeout(r, 400));
          const canvas = document.createElement('canvas');
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          canvas.getContext('2d').drawImage(video, 0, 0);
          stream.getTracks().forEach(t => t.stop());
          const data = canvas.toDataURL('image/png');
          return data;
        }
        captureFrame();
        ''')
        display(js)
        data = eval_js('captureFrame()')
        binary = b64decode(data.split(',')[1])
        img = Image.open(io.BytesIO(binary)).convert("RGB")
        self.last_frame = np.array(img)
        return self.last_frame

    def save_temp_frame(self, frame=None):
        if frame is None:
            frame = self.last_frame
        temp_path = tempfile.NamedTemporaryFile(suffix=".png", delete=False).name
        Image.fromarray(frame).save(temp_path)
        return temp_path

    def play_audio(self, path=None):
        if path is None:
            path = self.last_audio
        return Audio(path, autoplay=True)

"""# Face Recognition"""

class FaceRecognition:
    """
    A facial verification utility using DeepFace and PyTorch.
    It extracts facial embeddings, normalizes them, and verifies
    if a detected face matches any of the trusted individuals
    based on cosine similarity.
    """

    def __init__(self, trusted_individuals):
        self.trusted_individuals = torch.nn.functional.normalize(
            torch.tensor(trusted_individuals, dtype=torch.float32), p=2, dim=1
        )

    @staticmethod
    def get_embedding(path, detectionmodel="retinaface", recognitionmodel="VGG-Face", show_face=False):
        # Try normal detection first
        try:
            detections = DeepFace.extract_faces(
                img_path=path,
                detector_backend=detectionmodel,
                enforce_detection=True,
                align=True
            )
        except ValueError:
            # Fallback: allow no strict detection
            print("[Warning] No face detected strictly — retrying with enforce_detection=False")
            detections = DeepFace.extract_faces(
                img_path=path,
                detector_backend=detectionmodel,
                enforce_detection=False,
                align=True
            )

        if not detections:
            raise ValueError("No face detected in the image (even after fallback).")

        cropped_face = detections[0]["face"]
        rep = DeepFace.represent(
            img_path=cropped_face,
            model_name=recognitionmodel,
            enforce_detection=False
        )[0]["embedding"]

        emb = torch.tensor(rep, dtype=torch.float32)
        emb = torch.nn.functional.normalize(emb, p=2, dim=0)

        return emb

    @staticmethod
    def cosine_similarity(emb1, emb2):
        return torch.cosine_similarity(emb1.unsqueeze(0), emb2.unsqueeze(0))

    def is_trusted(self, path, detectionmodel="retinaface", recognitionmodel="VGG-Face", show_face=False, threshold=0.5):
        emb = self.get_embedding(path, detectionmodel, recognitionmodel, show_face)
        similarities = torch.cosine_similarity(emb.unsqueeze(0), self.trusted_individuals)
        return torch.any(similarities > threshold).item()

def save_image_embeddings(image_dir, output_dir="embeddings",
                          detectionmodel="retinaface", recognitionmodel="VGG-Face"):
    """
    Computes and stores facial embeddings for all .jpg images in a directory.
    Each image is processed through the FaceRecognition pipeline using the
    specified detection and recognition models, and the resulting normalized
    embeddings are saved as .pt files in the output directory.
    """
    os.makedirs(output_dir, exist_ok=True)
    fr = FaceRecognition(trusted_individuals=torch.empty(0, 512))
    for img_path in Path(image_dir).glob("*.jpg"):
        try:
            emb = fr.get_embedding(str(img_path), detectionmodel=detectionmodel, recognitionmodel=recognitionmodel)
            save_path = Path(output_dir) / f"{img_path.stem}_embedding.pt"
            torch.save(emb, save_path)
            print(f"Saved embedding for {img_path.name} → {save_path}")
        except Exception as e:
            print(f"Skipping {img_path.name}: {e}")

#save_image_embeddings("/content/drive/MyDrive/A2_EE782/Known_Faces")

def load_trusted_embeddings(embeddings_dir):
    """
    Loads all .pt embeddings from a given directory (e.g. Google Drive folder)
    and returns a single tensor of shape [N, D] for FaceRecognition.
    """
    embeddings = []
    for emb_path in Path(embeddings_dir).glob("*.pt"):
        try:
            emb = torch.load(emb_path, map_location="cpu")
            embeddings.append(emb)
            print(f"Loaded: {emb_path.name}")
        except Exception as e:
            print(f"Skipping {emb_path.name}: {e}")

    if not embeddings:
        raise ValueError("No valid embeddings found in the directory.")

    # Stack into a single tensor [N, D]
    trusted_tensor = torch.stack(embeddings)
    return trusted_tensor

"""# Command Recognition"""

class CommandRecognition:
    """
    A speech-command recognition system combining Whisper for speech-to-text,
    Kokoro for text-to-speech, and a zero-shot classifier for intent detection.
    It supports wake-word detection, natural command transcription,
    and classification into predefined intents such as 'guard' or 'stay idle'.
    """

    def __init__(self):
        self.commands = ["guard", "stay idle"]
        self.processor = AutoProcessor.from_pretrained("openai/whisper-small")
        self.model = AutoModelForSpeechSeq2Seq.from_pretrained("openai/whisper-small")
        self.tts_pipeline = KPipeline(lang_code='a')
        self.intent_classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

    def Speechtotext(self, audio_path):
        waveform, sr = torchaudio.load(audio_path)
        if sr != 16000:
            waveform = torchaudio.functional.resample(waveform, sr, 16000)
            sr = 16000
        waveform = waveform.squeeze().numpy()
        inputs = self.processor(waveform, sampling_rate=sr, return_tensors="pt")
        predicted_ids = self.model.generate(**inputs)
        transcription = self.processor.batch_decode(predicted_ids, skip_special_tokens=True)
        return transcription[0].lower()

    def wakeword(self, audio):
        txt = self.Speechtotext(audio)
        if "blueberry" in txt:
            return True
        else:
            return False

    def TexttoSpeech(self, text, voice='af_heart', outfile="output.wav"):
        generator = self.tts_pipeline(text, voice=voice)
        audio_data = None
        sample_rate = 24000
        for result in generator:
            if hasattr(result, "output") and hasattr(result.output, "audio"):
                audio_tensor = result.output.audio
                audio_data = audio_tensor.cpu().numpy()
                break
        if audio_data is not None:
            sf.write(outfile, audio_data, int(sample_rate))
            return outfile
        else:
            raise ValueError("Kokoro pipeline did not yield valid audio data.")

    def commandclassification(self, command):
        """Classify command as 'guard', 'stay idle', or 'unknown'."""
        result = self.intent_classifier(command, candidate_labels=self.commands)
        intent = result["labels"][0]
        confidence = result["scores"][0]
        if confidence < 0.5:
            intent = "unknown"
        return {"intent": intent, "confidence": confidence}

print("Requesting camera and microphone access...")

# These two lines will trigger browser permission requests once
media = ColabMedia(webcam_rate=1.5)
get_audio_input = media.get_audio_input
capture_webcam_frame = media.capture_webcam_frame
_ = capture_webcam_frame()
_ = get_audio_input()

print("Permissions granted! You can now safely proceed.\n")

"""## Basic Function test"""

# media = ColabMedia(webcam_rate=1.5)
# get_audio_input = media.get_audio_input
# capture_webcam_frame = media.capture_webcam_frame
# save_temp_frame = media.save_temp_frame
# play_audio = media.play_audio
# cmd = CommandRecognition()
# path = get_audio_input()
# frame = capture_webcam_frame()
# save_temp_frame(frame)
# play_audio(path)
# print("Speech to Text output:", cmd.Speechtotext(path))
# print("Wakeword detected:", cmd.wakeword(path))
# print("Command classification:", cmd.commandclassification("stt_output"))
# path1 = cmd.TexttoSpeech(text="This is a test", voice='af_heart')
# play_audio(path1)

"""# LLM"""

class LLM:
    """
    A lightweight interface for interacting with Google's Gemini API.
    It initializes a generative language model using a stored API key
    and provides configurable text generation with temperature,
    token limit, and sampling control.
    """

    def __init__(self, model_name="models/gemini-2.5-flash"):
        try:
            self.apikey = userdata.get("GOOGLE_API_KEY")
            if not self.apikey:
                raise ValueError("API key not found in Colab safekeys. Please set GEMINI_API_KEY.")
            genai.configure(api_key=self.apikey)
            self.model = genai.GenerativeModel(model_name)
        except Exception as e:
            print(f"Initialization error: {e}")
            self.model = None

    def generate_text(self, prompt, temperature=0.7, max_tokens=1000, top_p=0.9, top_k=40):
        if not self.model:
            return "Model not initialized properly."

        try:
            response = self.model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(
                    temperature=temperature,
                    max_output_tokens=max_tokens,
                    top_p=top_p,
                    top_k=top_k
                )
            )

            # 🧠 Try to extract text safely from candidates
            text = None
            if hasattr(response, "candidates") and response.candidates:
                for c in response.candidates:
                    if hasattr(c, "content") and hasattr(c.content, "parts"):
                        parts = [p.text for p in c.content.parts if hasattr(p, "text")]
                        if parts:
                            text = "\n".join(parts).strip()
                            break

            # 🔍 Handle blocked / empty responses
            if not text:
                finish_reason = getattr(response.candidates[0], "finish_reason", "unknown")
                feedback = getattr(response, "prompt_feedback", None)
                return f"[No usable text returned] finish_reason={finish_reason}, feedback={feedback}"

            return text

        except Exception as e:
            return f"API error: {e}"

"""# Graph"""

# --------------------------------------------
# Setup & Dependencies
# --------------------------------------------
media = ColabMedia(webcam_rate=1.5)
trusted_individuals = load_trusted_embeddings('/content/drive/MyDrive/A2_EE782/Known_Faces/Embeddings')
get_audio_input = media.get_audio_input
capture_webcam_frame = media.capture_webcam_frame
save_temp_frame = media.save_temp_frame
play_audio = media.play_audio

# --------------------------------------------
# Core Modules
# --------------------------------------------
face_recognition = FaceRecognition(trusted_individuals)
command_recognition = CommandRecognition()
llm = LLM()

# --------------------------------------------
# Shared state structure
# --------------------------------------------
class GuardState:
    mode: str = "Idle"
    last_command: str = ""
    is_trusted: bool = False
    escalation_level: int = 0

# --------------------------------------------
# LLM memory and response generation
# --------------------------------------------
memory = ConversationBufferMemory(return_messages=True)

def generate_guard_response(prompt):
    history = memory.load_memory_variables({})["history"]
    full_prompt = (
        "You are an AI security guard protecting a private room. "
        "Be firm, professional, and escalate gradually with unrecognized visitors.\n\n"
        "Conversation so far:\n" + str(history) + "\nUser: " + prompt
    )
    response = llm.generate_text(full_prompt)
    memory.save_context({"input": prompt}, {"output": response})
    return response

# --------------------------------------------
# State definitions
# --------------------------------------------
def idle_state(state: GuardState):
    audio = get_audio_input()
    detected = command_recognition.wakeword(audio)
    if detected:
        state.mode = "Listening"
        return state, "wakeword_detected"
    return state, "stay_idle"

def listening_state(state: GuardState):
    audio = get_audio_input()
    command = command_recognition.Speechtotext(audio)
    state.last_command = command.lower()
    detected_command = command_recognition.commandclassification(command)

    intent = detected_command["intent"]
    if intent == "unknown":
        return state, "unknown_command"
    elif intent == "guard":
        state.mode = "GuardMode"
        return state, "activate_guard"
    elif intent == "stay idle":
        state.mode = "Idle"
        return state, "deactivate_guard"

def guard_mode_state(state: GuardState):
    frame = capture_webcam_frame()
    face_path = save_temp_frame(frame)
    if not face_recognition.is_trusted(face_path):
        state.escalation_level += 1
        state.is_trusted = False
        state.mode = "Speaking"
        return state, "intruder_detected"
    else:
        state.is_trusted = True
        return state, "trusted_person"

def speaking_state(state: GuardState):
    if not state.is_trusted:
        level_prompts = [
            "Who are you? This room is restricted.",
            "You are not recognized. Please identify yourself.",
            "This is a final warning. Leave immediately, or I will raise an alarm."
        ]
        state.escalation_level = min(state.escalation_level, 3)
        prompt = level_prompts[state.escalation_level - 1]
        response = generate_guard_response(prompt)
        outfile = command_recognition.TexttoSpeech(response)
        play_audio(outfile)

    state.mode = "GuardMode"
    return state, "back_to_guarding"

# --------------------------------------------
# Graph Assembly
# --------------------------------------------
graph = StateGraph(GuardState)
graph.add_node("Idle", idle_state)
graph.add_node("Listening", listening_state)
graph.add_node("GuardMode", guard_mode_state)
graph.add_node("Speaking", speaking_state)

graph.add_edge("Idle", "Listening")
graph.add_edge("Listening", "GuardMode")
graph.add_edge("Listening", "Idle")
graph.add_edge("GuardMode", "Speaking")
graph.add_edge("Speaking", "GuardMode")

graph.set_entry_point("Idle")
graph.set_finish_point("Speaking")

app = graph.compile()

def plot_state_graph(graph):
    dot = Digraph(comment="Guard State Graph", format="png")
    dot.attr(rankdir="LR", size="8,5")
    for node_name in graph.nodes.keys():
        dot.node(node_name, node_name, shape="ellipse", style="filled", fillcolor="lightgray")
    for edge in graph.edges:
        src, dst = edge
        dot.edge(src, dst)
    # Removed lines that caused AttributeError
    # dot.node("START", shape="circle", style="filled", fillcolor="green")
    # dot.node("END", shape="doublecircle", style="filled", fillcolor="red")
    # dot.edge("START", graph.entry_point)
    # dot.edge(graph.finish_point, "END")
    return dot
dot = plot_state_graph(graph)
dot.render("/content/guard_state_graph", view=True)
dot

"""# Inference"""

# -------------------------------
# Inference Loop for AI Guard
# -------------------------------

def run_guard_system():
    state = GuardState()
    current_state = "Idle"

    print("[SYSTEM] AI Guard initialized. Starting in Idle mode...")

    while True:
        if current_state == "Idle":
            print("[STATE] Idle: Waiting for wakeword...")
            state, signal = idle_state(state)
            if signal == "wakeword_detected":
                print("[EVENT] Wakeword detected! Moving to Listening...")
                current_state = "Listening"

        elif current_state == "Listening":
            print("[STATE] Listening: Waiting for command...")
            state, signal = listening_state(state)

            if signal == "activate_guard":
                print("[EVENT] Activating Guard Mode.")
                current_state = "GuardMode"

            elif signal == "deactivate_guard":
                print("[EVENT] Command to stay idle received.")
                current_state = "Idle"

            elif signal == "unknown_command":
                print("[EVENT] Unknown command. Returning to Idle.")
                current_state = "Idle"

        elif current_state == "GuardMode":
            print("[STATE] Guard Mode: Monitoring environment...")
            frame = capture_webcam_frame()

            # Wakeword interrupt check (always available)
            audio = get_audio_input()
            if command_recognition.wakeword(audio):
                print("[INTERRUPT] Wakeword detected! Switching to Listening mode.")
                current_state = "Listening"
                continue

            # Face recognition loop
            face_path = save_temp_frame(frame)
            if not face_recognition.is_trusted(face_path):
                print("[EVENT] Unrecognized face detected! Escalating.")
                state.is_trusted = False
                state.escalation_level += 1
                current_state = "Speaking"
            else:
                state.is_trusted = True
                state.escalation_level = 0
                print("[STATUS] Trusted individual confirmed.")
                # Continue staying in guard mode

        elif current_state == "Speaking":
            print("[STATE] Speaking: Responding to potential intruder...")
            state, signal = speaking_state(state)

            if signal == "back_to_guarding":
                print("[EVENT] Response complete. Returning to Guard Mode.")
                current_state = "GuardMode"

        else:
            print(f"[ERROR] Unknown state encountered: {current_state}")
            current_state = "Idle"

run_guard_system()

